[feat] Create event on mobile app
ultras-io/ultras pull request #233
Opened 2022-09-22 19:46 UTC by rado196

Create events functionality in mobile app.

This PR also includes:
1) Upgrading `React` and `React Native` to the latest versions (to fix build error: `ultras.app/Frameworks/RCTVibration.framework/Info.plist: no such file or directory`).
2) Upgrading packages to the latest versions.
3) Enabling `Hermes` JavaScript engine.
4) Typo fixes.

2022-09-22 20:45 UTC, hay92k requested changes

2022-09-22 20:45 UTC, hay92k commented on clients/app/src/views/components/base/FormControl/FormControl.tsx
> +const FormControl: React.FC<IFormControlProps> = ({ children }) => {
not the best name for this component

2022-09-22 20:45 UTC, hay92k commented on clients/app/src/views/components/base/Icon/Icon.tsx
> +      <SvgXml xml={icons[name].content} fill={colors[color]} />
why we need this?
Isn't it bring bugs?

2022-09-22 20:45 UTC, hay92k commented on clients/app/src/views/components/base/RemoveButton/types.ts
> +export interface RemoveButtonInterface {
why nor IRemoveButtonProps

2022-09-23 19:30 UTC, rado196 commented on clients/app/src/views/components/base/Icon/Icon.tsx
> +      <SvgXml xml={icons[name].content} fill={colors[color]} />
that's required by hermes

2022-09-23 19:36 UTC, rado196 commented on clients/app/src/views/components/base/RemoveButton/types.ts
> +export interface RemoveButtonInterface {
will change

2022-09-23 19:55 UTC, rado196 commented on clients/app/src/views/components/base/FormControl/FormControl.tsx
> +const FormControl: React.FC<IFormControlProps> = ({ children }) => {
will update to `InputSection`

2022-09-23 20:08 UTC, hay92k approved these changes
lgtm

2022-09-24 07:07 UTC, merged