[feat] change match during event create.
ultras-io/ultras pull request #235
Opened 2022-09-27 21:34 UTC by rado196

This PR includes:

---

✅ Already completed:
- Create nested navigation for `CreateEvent` screen:
  - __the screen opened with `presentation: 'modal'` options and to make navigation inside of modal we need to create nested navigation, otherwise, root navigation will be changed__
- `SelectMatch` screen with match list.
- Move the event store into a separate file to make it available on both screens (`CreateEvent` and `SelectMatch`).
- Added the ability to disable press on the team icon on the `MatchInfo` component.

---

🚧 Need to develop:
- Search matches.
- Load the next page of matches on the scroll end.

2022-09-29 14:35 UTC, hay92k requested changes

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/i18n/locales/en.ts
> +  'common-back': 'Back',
remove and replace with icon

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/CreateEventWrapper.tsx
> +import React from 'react';
no need for Wrapper, merge with navigation

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/components/BackButtonComponent.tsx
> +import React from 'react';
move to global

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/navigation.tsx
> +// order is important !!!
it does not.

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/navigation.tsx
> +const currentTabName = 'CreateEvent';
remove this, use useNavigationWithParams hook.

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/screens/CreateEvent/components/SelectedMatchComponent.tsx
> +  const navigation = useNavigation<any>();
use useNavigationWithParams hook

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/screens/SelectMatch/components/SelectMatchComponent.tsx
> +          <Box alignItems="center" paddingTop="4" paddingBottom="10">
change to Loader Component

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/CreateEvent/screens/SelectMatch/styles.ts
> +import { StyleSheet } from 'react-native';
move to bottom of file.

2022-09-29 14:35 UTC, hay92k commented on clients/app/src/views/screens/Home/components/AddActionSheet.tsx
> +    (screen: any, params?: any) => {
don't clear why we need this

2022-10-02 10:43 UTC, rado196 commented on clients/app/src/i18n/locales/en.ts
> +  'common-back': 'Back',
okay :)

2022-10-02 10:53 UTC, rado196 commented on clients/app/src/views/screens/CreateEvent/components/BackButtonComponent.tsx
> +import React from 'react';
good idea

2022-10-02 11:06 UTC, rado196 commented on clients/app/src/views/screens/CreateEvent/screens/CreateEvent/components/SelectedMatchComponent.tsx
> +  const navigation = useNavigation<any>();
updated.

2022-10-02 11:31 UTC, rado196 commented on clients/app/src/views/screens/CreateEvent/screens/SelectMatch/components/SelectMatchComponent.tsx
> +          <Box alignItems="center" paddingTop="4" paddingBottom="10">
updated

2022-10-02 11:33 UTC, rado196 commented on clients/app/src/views/screens/CreateEvent/screens/SelectMatch/styles.ts
> +import { StyleSheet } from 'react-native';
done

2022-10-02 11:34 UTC, rado196 commented on clients/app/src/views/screens/Home/components/AddActionSheet.tsx
> +    (screen: any, params?: any) => {
unnecessary params are removed

2022-10-03 20:46 UTC, hay92k approved these changes
lgtm

2022-10-03 20:46 UTC, merged